const http=require('http');
const fs=require('fs');
const path=require('path');
const url=require('url');
const crypto=require('crypto');
const {spawn}=require('child_process');
const {createClient}=require('@supabase/supabase-js');

const PORT=process.env.PORT||3000;
const ROOT=__dirname;
const SUPABASE_URL=process.env.SUPABASE_URL;
const SUPABASE_KEY=process.env.SUPABASE_SERVICE_ROLE_KEY||process.env.SUPABASE_ANON_KEY;
if(!SUPABASE_URL||!SUPABASE_KEY){console.error('Faltan SUPABASE_URL y SUPABASE_SERVICE_ROLE_KEY/SUPABASE_ANON_KEY.');process.exit(1)}
const db=createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{autoRefreshToken:false,persistSession:false}});
const mime={'.html':'text/html; charset=utf-8','.js':'application/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json; charset=utf-8','.webmanifest':'application/manifest+json'};
const send=(res,code,data,type='application/json; charset=utf-8')=>{res.writeHead(code,{'Content-Type':type,'Cache-Control':'no-store'});res.end(typeof data==='string'||Buffer.isBuffer(data)?data:JSON.stringify(data))};
function body(req){return new Promise((resolve,reject)=>{let b='';req.on('data',c=>{b+=c;if(b.length>1024*1024)req.destroy(new Error('Body demasiado grande'))});req.on('end',()=>{try{resolve(b?JSON.parse(b):{})}catch{reject(new Error('JSON no válido'))}});req.on('error',reject)})}
function houseIdValid(id){return /^[A-Za-z0-9_-]{4,32}$/.test(id)}
function adminKeyValid(req){return process.env.ADMIN_KEY&&req.headers['x-admin-key']===process.env.ADMIN_KEY}
function randomHouseId(){const alphabet='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';const bytes=crypto.randomBytes(10);return [...bytes].map(b=>alphabet[b%alphabet.length]).join('')}

async function ensureHouse(id,name){const {data,error}=await db.from('houses').upsert({id,name:name||`Casa ${id}`},{onConflict:'id',ignoreDuplicates:true}).select().maybeSingle();if(error)throw error;if(data)return data;const r=await db.from('houses').select('id,name').eq('id',id).single();if(r.error)throw r.error;return r.data}
async function getHouse(id){const {data,error}=await db.from('houses').select('id,name').eq('id',id).maybeSingle();if(error)throw error;return data}
async function getItems(id){const {data,error}=await db.from('shopping_items').select('id,product_id,texto,formato,categoria,subcategoria,ruta,pagina,cantidad,created_at,updated_at').eq('house_id',id).order('created_at',{ascending:true});if(error)throw error;return(data||[]).map(x=>({id:x.id,productId:x.product_id,texto:x.texto,formato:x.formato||'',categoria:x.categoria||'',subcategoria:x.subcategoria||'',ruta:x.ruta||'',pagina:x.pagina??null,cantidad:x.cantidad}))}
async function getHistory(id){const {data,error}=await db.from('purchases').select('id,purchased_at,items').eq('house_id',id).order('purchased_at',{ascending:false}).limit(30);if(error)throw error;return(data||[]).map(x=>({id:x.id,date:x.purchased_at,items:x.items||[]}))}
async function getHouseState(id){const house=await getHouse(id);if(!house)return null;const [items,history]=await Promise.all([getItems(id),getHistory(id)]);return{id:house.id,name:house.name,items,history}}
async function addItem(houseId,b){if(!b.productId||!b.texto)throw new Error('Datos incompletos');const quantity=Math.max(1,Math.min(99,Number(b.cantidad)||1));const {data:existing,error:findError}=await db.from('shopping_items').select('id,cantidad').eq('house_id',houseId).eq('product_id',b.productId).maybeSingle();if(findError)throw findError;if(existing){const {data,error}=await db.from('shopping_items').update({cantidad:Math.min(99,existing.cantidad+quantity),formato:b.formato??'',subcategoria:b.subcategoria??'',ruta:b.ruta??'',updated_at:new Date().toISOString()}).eq('id',existing.id).select().single();if(error)throw error;return data}const {data,error}=await db.from('shopping_items').insert({house_id:houseId,product_id:b.productId,texto:b.texto,formato:b.formato||'',categoria:b.categoria||'',subcategoria:b.subcategoria||'',ruta:b.ruta||'',pagina:b.pagina??null,cantidad:quantity}).select().single();if(error)throw error;return data}
async function updateItem(houseId,productId,quantity){const q=Math.max(0,Math.min(99,Number(quantity)||0));if(q===0){const {error}=await db.from('shopping_items').delete().eq('house_id',houseId).eq('product_id',productId);if(error)throw error;return}const {error}=await db.from('shopping_items').update({cantidad:q,updated_at:new Date().toISOString()}).eq('house_id',houseId).eq('product_id',productId);if(error)throw error}
async function purchaseHouse(houseId){const items=await getItems(houseId);if(!items.length)throw new Error('La cesta está vacía');const {data:purchase,error:purchaseError}=await db.from('purchases').insert({house_id:houseId,items}).select('id,purchased_at,items').single();if(purchaseError)throw purchaseError;const {error:deleteError}=await db.from('shopping_items').delete().eq('house_id',houseId);if(deleteError)throw deleteError;return{id:purchase.id,date:purchase.purchased_at,items:purchase.items}}

function catalogPayloadFromRows(rows){const products=(rows||[]).map(x=>({id:x.id,codigo:x.codigo,texto:x.texto,formato:x.formato||'',packaging:x.packaging||'',categoria:x.categoria||'',subcategoria:x.subcategoria||'',ruta:x.ruta||'',pagina:x.pagina??null,imagen:x.imagen||''}));const categories=[...new Set(products.map(p=>p.categoria).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'es'));return{source:'Supabase · catálogo Mercadona',updatedAt:rows?.length?rows.reduce((m,x)=>x.updated_at>m?x.updated_at:m,''):null,count:products.length,categories,products}}
async function readCatalogFromDb(){let rows=[];const pageSize=1000;for(let from=0;;from+=pageSize){const {data,error}=await db.from('catalog_products').select('id,codigo,texto,formato,packaging,categoria,subcategoria,ruta,pagina,imagen,updated_at').order('id',{ascending:true}).range(from,from+pageSize-1);if(error)throw error;if(data?.length)rows.push(...data);if(!data||data.length<pageSize)break}return catalogPayloadFromRows(rows)}
async function readLocalCatalog(){const file=path.join(ROOT,'data','catalogo.json');if(!fs.existsSync(file))return null;try{return JSON.parse(fs.readFileSync(file,'utf8'))}catch{return null}}
async function persistCatalog(catalog){const products=Array.isArray(catalog?.products)?catalog.products:[];if(products.length<500)throw new Error(`Catálogo inválido: solo ${products.length} productos.`);const rows=products.map(p=>({id:String(p.id),codigo:String(p.codigo||p.id),texto:String(p.texto||''),formato:String(p.formato||''),packaging:String(p.packaging||''),categoria:String(p.categoria||''),subcategoria:String(p.subcategoria||''),ruta:String(p.ruta||''),pagina:p.pagina??null,imagen:String(p.imagen||''),updated_at:new Date().toISOString()}));for(let i=0;i<rows.length;i+=500){const {error}=await db.from('catalog_products').upsert(rows.slice(i,i+500),{onConflict:'id'});if(error)throw error}return{count:rows.length,imageCount:rows.filter(x=>x.imagen).length}}
let syncPromise=null;
async function syncCatalog(){if(syncPromise)return syncPromise;syncPromise=new Promise((resolve,reject)=>{const cp=spawn(process.execPath,[path.join(ROOT,'sync-catalog.js')],{cwd:ROOT,stdio:['ignore','pipe','pipe']});let err='';cp.stderr.on('data',d=>err+=d);cp.stdout.on('data',d=>process.stdout.write(d));cp.on('close',async code=>{if(code!==0)return reject(new Error(err||'No se pudo actualizar el catálogo'));try{const local=await readLocalCatalog();if(!local)throw new Error('El sincronizador no generó data/catalogo.json');const saved=await persistCatalog(local);resolve({catalog:catalogPayloadFromRows(local.products?.map(p=>({...p,updated_at:new Date().toISOString()}))),...saved})}catch(e){reject(e)}})}).finally(()=>{syncPromise=null});return syncPromise}
async function readCatalog(){const dbCatalog=await readCatalogFromDb();if(dbCatalog.count>0)return dbCatalog;const local=await readLocalCatalog();if(local?.products?.length){await persistCatalog(local);return catalogPayloadFromRows(local.products.map(p=>({...p,updated_at:new Date().toISOString()})))}throw new Error('El catálogo todavía no está cargado en Supabase. Entra una vez en Administración y pulsa «Actualizar catálogo con fotos».')}

const server=http.createServer(async(req,res)=>{try{const u=url.parse(req.url,true);const p=u.pathname;
if(p==='/health'&&req.method==='GET')return send(res,200,{ok:true,database:'supabase',catalog:'supabase'});
if(p==='/api/catalog'&&req.method==='GET')return send(res,200,await readCatalog());
if(p==='/api/catalog/sync'&&req.method==='POST'){if(!adminKeyValid(req))return send(res,403,{error:'No autorizado'});const d=await syncCatalog();return send(res,200,{count:d.count,imageCount:d.imageCount,products:d.catalog.products,categories:d.catalog.categories,updatedAt:d.catalog.updatedAt})}
let m=p.match(/^\/api\/house\/([^/]+)$/);if(m&&req.method==='GET'){const id=decodeURIComponent(m[1]);if(!houseIdValid(id))return send(res,400,{error:'Identificador de casa no válido'});await ensureHouse(id);return send(res,200,await getHouseState(id))}
if(p==='/api/admin/house'&&req.method==='POST'){if(!adminKeyValid(req))return send(res,403,{error:'No autorizado'});const b=await body(req);const id=String(b.id||randomHouseId()).trim().toUpperCase();if(!houseIdValid(id))return send(res,400,{error:'ID no válido. Usa 4-32 letras/números.'});const house=await ensureHouse(id,b.name||`Casa ${id}`);const base=process.env.PUBLIC_BASE_URL||`https://${req.headers.host}`;return send(res,201,{...house,url:`${base.replace(/\/$/,'')}/casa/${encodeURIComponent(house.id)}`})}
m=p.match(/^\/api\/house\/([^/]+)\/item$/);if(m&&req.method==='POST'){const id=decodeURIComponent(m[1]);if(!houseIdValid(id))return send(res,400,{error:'Casa no válida'});await ensureHouse(id);return send(res,200,{ok:true,item:await addItem(id,await body(req))})}
m=p.match(/^\/api\/house\/([^/]+)\/item\/([^/]+)$/);if(m){const id=decodeURIComponent(m[1]),productId=decodeURIComponent(m[2]);if(!houseIdValid(id))return send(res,400,{error:'Casa no válida'});await ensureHouse(id);if(req.method==='PATCH'){const b=await body(req);await updateItem(id,productId,b.cantidad);return send(res,200,{ok:true})}if(req.method==='DELETE'){const {error}=await db.from('shopping_items').delete().eq('house_id',id).eq('product_id',productId);if(error)throw error;return send(res,200,{ok:true})}}
m=p.match(/^\/api\/house\/([^/]+)\/purchase$/);if(m&&req.method==='POST'){const id=decodeURIComponent(m[1]);if(!houseIdValid(id))return send(res,400,{error:'Casa no válida'});if(!await getHouse(id))return send(res,404,{error:'Casa no encontrada'});return send(res,200,{ok:true,purchase:await purchaseHouse(id)})}
const file=p==='/'?'/index.html':p;const publicRoot=path.join(ROOT,'public');const fp=path.normalize(path.join(publicRoot,file));if(!fp.startsWith(publicRoot))return send(res,403,{error:'Forbidden'});if(fs.existsSync(fp)&&fs.statSync(fp).isFile()){const ext=path.extname(fp);res.writeHead(200,{'Content-Type':mime[ext]||'application/octet-stream'});return fs.createReadStream(fp).pipe(res)}const index=path.join(publicRoot,'index.html');res.writeHead(200,{'Content-Type':mime['.html']});return fs.createReadStream(index).pipe(res)
}catch(e){console.error(e);return send(res,500,{error:e.message||'Error interno'})}});
server.listen(PORT,'0.0.0.0',()=>console.log(`CompraNFC listo en el puerto ${PORT}`));
