const http=require('http'),fs=require('fs'),path=require('path'),url=require('url'),crypto=require('crypto');
const PORT=process.env.PORT||3000, ROOT=__dirname, DATA=path.join(ROOT,'data'), STATE=path.join(DATA,'state.json');
fs.mkdirSync(DATA,{recursive:true}); if(!fs.existsSync(STATE)) fs.writeFileSync(STATE,JSON.stringify({houses:{demo:{name:'Casa demo',items:{},history:[]}}},null,2));
const mime={'.html':'text/html; charset=utf-8','.js':'application/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json; charset=utf-8','.webmanifest':'application/manifest+json','.png':'image/png','.svg':'image/svg+xml'};
const send=(res,code,data,type='application/json; charset=utf-8')=>{res.writeHead(code,{'Content-Type':type,'Cache-Control':'no-store'});res.end(typeof data==='string'||Buffer.isBuffer(data)?data:JSON.stringify(data));};
const load=()=>JSON.parse(fs.readFileSync(STATE,'utf8')); const save=s=>fs.writeFileSync(STATE,JSON.stringify(s,null,2));
function body(req){return new Promise((resolve,reject)=>{let b='';req.on('data',c=>b+=c);req.on('end',()=>{try{resolve(b?JSON.parse(b):{})}catch(e){reject(e)}})})}
function house(id){return /^[A-Za-z0-9_-]{2,64}$/.test(id)}
const server=http.createServer(async(req,res)=>{try{const u=url.parse(req.url,true),p=u.pathname;
 if(p==='/api/catalog'&&req.method==='GET') return send(res,200,fs.readFileSync(path.join(DATA,'catalogo.json')),'application/json; charset=utf-8');
 if(p==='/api/catalog/sync'&&req.method==='POST'){const {spawn}=require('child_process');return new Promise(resolve=>{const cp=spawn(process.execPath,[path.join(ROOT,'sync-catalog.js')],{cwd:ROOT,stdio:['ignore','pipe','pipe']});let err='';cp.stderr.on('data',d=>err+=d);cp.on('close',code=>{if(code!==0)return (send(res,502,{error:err||'No se pudo actualizar el catálogo'}),resolve());try{const d=JSON.parse(fs.readFileSync(path.join(DATA,'catalogo.json'),'utf8'));send(res,200,{count:d.products.length,products:d.products});}catch(e){send(res,500,{error:e.message})}resolve()})})}
 let m=p.match(/^\/api\/house\/([^/]+)$/); if(m){let id=m[1];if(!house(id))return send(res,400,{error:'Casa no válida'});let s=load();s.houses[id]??={name:'Casa '+id,items:{},history:[]};save(s);if(req.method==='GET')return send(res,200,{id,name:s.houses[id].name,items:Object.values(s.houses[id].items),history:s.houses[id].history.slice(0,20)});}
 m=p.match(/^\/api\/house\/([^/]+)\/item$/);if(m&&req.method==='POST'){let id=m[1],b=await body(req);if(!house(id)||!b.productId||!b.texto)return send(res,400,{error:'Datos incompletos'});let s=load(),h=s.houses[id]??={name:'Casa '+id,items:{},history:[]};let q=Math.max(1,Math.min(99,Number(b.cantidad)||1));if(h.items[b.productId]){h.items[b.productId].cantidad=Math.min(99,h.items[b.productId].cantidad+q);if(b.formato)h.items[b.productId].formato=b.formato;if(b.ruta)h.items[b.productId].ruta=b.ruta;if(b.subcategoria)h.items[b.productId].subcategoria=b.subcategoria;}else h.items[b.productId]={productId:b.productId,texto:b.texto,formato:b.formato||'',categoria:b.categoria||'',subcategoria:b.subcategoria||'',ruta:b.ruta||'',pagina:b.pagina||null,cantidad:q,addedAt:new Date().toISOString()};save(s);return send(res,200,{ok:true,item:h.items[b.productId]});}
 m=p.match(/^\/api\/house\/([^/]+)\/item\/([^/]+)$/);if(m){let id=m[1],pid=m[2],s=load(),h=s.houses[id];if(!h)return send(res,404,{error:'Casa no encontrada'});if(req.method==='PATCH'){let b=await body(req),q=Math.max(0,Math.min(99,Number(b.cantidad)||0));if(q===0)delete h.items[pid];else if(h.items[pid])h.items[pid].cantidad=q;save(s);return send(res,200,{ok:true});}if(req.method==='DELETE'){delete h.items[pid];save(s);return send(res,200,{ok:true});}}
 m=p.match(/^\/api\/house\/([^/]+)\/purchase$/);if(m&&req.method==='POST'){let id=m[1],s=load(),h=s.houses[id];if(!h)return send(res,404,{error:'Casa no encontrada'});let items=Object.values(h.items);if(!items.length)return send(res,400,{error:'La cesta está vacía'});let purchase={id:crypto.randomUUID(),date:new Date().toISOString(),items};h.history.unshift(purchase);h.history=h.history.slice(0,30);h.items={};save(s);return send(res,200,{ok:true,purchase});}
 let file=p==='/'?'/index.html':p;let fp=path.normalize(path.join(ROOT,'public',file));if(!fp.startsWith(path.join(ROOT,'public')))return send(res,403,{error:'Forbidden'});if(fs.existsSync(fp)&&fs.statSync(fp).isFile()){let ext=path.extname(fp);res.writeHead(200,{'Content-Type':mime[ext]||'application/octet-stream'});return fs.createReadStream(fp).pipe(res)}return fs.createReadStream(path.join(ROOT,'public','index.html')).pipe(res);
}catch(e){console.error(e);send(res,500,{error:e.message})}});
server.listen(PORT,'0.0.0.0',()=>console.log(`\nCompraNFC: http://localhost:${PORT}/casa/demo\n`));
